# Generated by Django 4.2.4 on 2024-10-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_system', '0002_remove_service_price_service_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
